### PR TITLE
Kf/serializable annotations from multi2oie

### PR DESCRIPTION
**Pull request by KasperFyhn**
This PR introduces a different way of storing relation triplet on `Doc` objects. The original reason for doing this was to avoid storing the triplets as tuples of `Span` objects since `Span`s are not serializable which is a requirement for running a multiprocessing SpaCy pipeline. As I started looking into, it turned out to have some other nice features, e.g. not storing redundant data as all the magic happens in _getter_ lambdas.

With these changes the SpaCy pipeline can be run using multiple CPU cores, as in the test case I have added. However, there is a challenge with pytorch that runs on multiple threads which must therefore be limited to one thread per process. You can do something like this:
```py
nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("relation_extractor")

test_sents = ["Mette Frederiksen is the Danish politician."] * 1000

torch.set_num_threads(1)
pipe = nlp.pipe(test_sents, n_process=os.cpu_count(), batch_size=25)
```

### CODE REVIEW

**Comment by KasperFyhn** [comment]
The changes seem to break some things when a full test run is made due some conflicting assumptions about the `relation_triplets` extension across the project. I'll fix that!

**Comment by KennethEnevoldsen** [comment]
Så fin ændring, men vil torch ikke bare parallisere forward pass'et? (jeg er bange for denne metode blot er langsommere) - derfor er det dog vigtigt at det kan serialises.

**Comment by KennethEnevoldsen** [comment]
En anden ting er at jeg ikke er sikker på de to relationsship extraction pipelines har lignende output (den anden output ser anderledes ud)

**Review by KennethEnevoldsen — COMMENTED** [review]
-

**Review by rbkhb — APPROVED** [review]

**Comment by KasperFyhn** [comment]
> Så fin ændring, men vil torch ikke bare parallisere forward pass'et? (jeg er bange for denne metode blot er langsommere) - derfor er det dog vigtigt at det kan serialises.

A relevant concern if it is necessarily a speed-up to parallelize the SpaCy pipeline. And yes, there is some parallelization going on in pytorch. I think it depends on various factors what is ultimately the fastest - document length, hardware setup (I don't have dedicated GPU in my work laptop, for instance) among other things. Multiprocessing can help squeeze out some CPU juice, but also involves a bit of overhead with serialization and can sometimes throttle/bottleneck other things. But with some initial experiments on short documents, it seemed to be a notable speed-up.

> En anden ting er at jeg ikke er sikker på de to relationsship extraction pipelines har lignende output (den anden output ser anderledes ud)

Yeah, I noticed that I had not done my homework all too well after the failing tests. I'll try to see if I can streamline or if there is another good way. Ideally, we want the format of the output to be the same regardless of the specific component anyway.

**Comment by KennethEnevoldsen** [comment]
> Multiprocessing can help squeeze out some CPU juice, but also involves a bit of overhead with serialization and can sometimes throttle/bottleneck other things. But with some initial experiments on short documents, it seemed to be a notable speed-up.

Perfect. Have had mixed experiences with it myself with spacy so just wanted to let you know that it wasn't always a speedup

> Yeah, I noticed that I had not done my homework all too well after the failing tests. I'll try to see if I can streamline or if there is another good way. Ideally, we want the format of the output to be the same regardless of the specific component anyway.

Yea exactly. It might be worth introducing an output object (e.g. using a [typed dict](https://peps.python.org/pep-0589/)) such that it remains a default type.

**Pull request merged**
