### PR TITLE
Draft for supernodes collection and script for the ranked list of heads creation

### PR DESCRIPTION
**Pull request by esborisova**
A) I added a few lines for creating and saving a ranked list of heads 

B) I cannot come up with a good pipeline structure for supernodes collection where:

1. it is possible to continue collecting the seeds for a supernode (see comments on lines 42, 46)
2. seeds which have been stemmed before do not go through this process again (line 30)

Any suggestions on how to restructure the script will be helpful. 

I took the list of heads/ents from the supplement to the paper. We can further compare the results with their supernodes. 

In the paper, the steps are described on page 13. Stephan and I also figured out what exactly should be done and documented it [here](https://docs.google.com/document/d/1yUwN9jOpyN3sK6LpCS-tO_Nb-Y3CdqtvSrqugJTDDs8/edit).

### CODE REVIEW

**Comment by esborisova** [comment]
@KennethEnevoldsen 
I tested the script we wrote. It works almost perfectly except the substrings collection step we discussed. 
F.ex., if we have **democrats** as a seed, then strings such as **democrat** and **democratic** should be collected. And the final set of seeds will be **{democrats, democrat, democratic}**. 
We need a stemmer since the lemmatizer will return those words as they are and they won't be considered as substrings. I added stemming to the code but is't for English.
You mentioned that there is a problem with stemmers for Danish, what are the options?

**Comment by KennethEnevoldsen** [comment]
> F.ex., if we have democrats as a seed, then strings such as democrat and democratic should be collected. And the final set of seeds will be {democrats, democrat, democratic}.

I agree with democrat (that could be solved using lemmatization), but I am not sure I agree with democratic. What is @rbkhb opinion on this?

> You mentioned that there is a problem with stemmers for Danish, what are the options?

I am not aware of any Danish stemmers (the sentida package seemingly uses the snowballstemmer).

**Comment by esborisova** [comment]
> > F.ex., if we have democrats as a seed, then strings such as democrat and democratic should be collected. And the final set of seeds will be {democrats, democrat, democratic}.
> 
> I agree with democrat (that could be solved using lemmatization), but I am not sure I agree with democratic. What is @rbkhb opinion on this?
> 
I understand why and I also have doubts about that. But in the paper on page 22 they have this supernode as an example 
[’authority’, ’author’, ’authorizing’, ’authorities’, ’authors’, ’authorization’, ’port’, 'executive’] and they stem entities in their code.

**Comment by KennethEnevoldsen** [comment]
Add lemmatization and stemming and make stemming an optional argument in the function. It should then be easy to toggle

**Comment by esborisova** [comment]
> Add lemmatization and stemming and make stemming an optional argument in the function. It should then be easy to toggle

**Comment by rbkhb** [comment]
>

**Comment by rbkhb** [comment]
> > > F.ex., if we have democrats as a seed, then strings such as democrat and democratic should be collected. And the final set of seeds will be {democrats, democrat, democratic}.
> > 
> > 
> > I agree with democrat (that could be solved using lemmatization), but I am not sure I agree with democratic. What is @rbkhb opinion on this?
> 
> I understand why and I also have doubts about that. But in the paper on page 22 they have this supernode as an example [’authority’, ’author’, ’authorizing’, ’authorities’, ’authors’, ’authorization’, ’port’, 'executive’]. But I am not sure whether this list is the result of clustering. They both stem and lemmatize entities in their code.

This set ['authority'...and related words] has to be partially the result of clustering. Stemming and lemmatizing e.g. 'democrats', as @KennethEnevoldsen points out, would produce 'democrat' and 'democrats' but not 'democratic'.

**Comment by esborisova** [comment]
Alright, then what is the best lemmatizer for Danish @KennethEnevoldsen ?
For English I've tried both, spaCy and WordNet. The former returns "democrat", "democrats", "democratic", while the letter gives what we want "democrat", "democrat", "democratic".

**Comment by KennethEnevoldsen** [comment]
Use spacy. It fits with the existing pipeline and is easy to update if we need it (its fallback is also good).

**Pull request closed without merging**
